version: "3.3"
services:
    web:
        build:
            args:
                version: 0.0.1
            context: .
            dockerfile: web/Dockerfile
        expose:
            - 4200
        ports:
            - "4200:4200"