---
#System Settings
php_modules: [
  'libapache2-mod-php', 
  'php-json',
  'php-curl', 
  'php-gd', 
  'php-mbstring', 
  'php-xml', 
  'php-xmlrpc', 
  'php-soap', 
  'php-intl', 
  'php-zip',
  'php-bcmath',
  'php-curl',
  'php-imagick',
  'php-mysql' 
]

#MySQL Settings
mysql_root_password: "corefinder"
mysql_db: "wordpress"
mysql_user: "airdroid"
mysql_password: "corefinder89"

#HTTP Settings
http_host: "127.0.0.1"
http_conf: "default"
http_port: "80"