apiVersion: v1
kind: Pod
metadata:
 name: multi-container
spec:
 containers:
  - image: nginx
    name: c1
    ports:
    - containerPort: 80
  - image: tomcat
    name: c2
    ports:
    - containerPort: 8080